name: Build/Release

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Set up build environment (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install make

      - name: Set up build environment (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install make

      - name: Build project
        run: make

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: catsoup-binary-${{ matrix.os }}
          path: ./catsoup

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up GitHub CLI
        uses: actions/setup-go@v3
        with:
          go-version: "^1.18"

      - name: Create Release
        run: |
          gh release create ${{ github.ref }} --repo "${{ github.repository }}" --title "Release ${{ github.ref }}" --generate-notes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
