name: Build/Release

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        arch: [x86_64, arm64]
        exclude:
          - os: macos-latest
            arch: x86_64
          - os: windows-latest
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment (Ubuntu)
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Set up build environment (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install make

      - name: Set up build environment (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install make

      - name: Build project
        run: make TARGET_ARCH=${{ matrix.arch }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: catsoup-${{ matrix.os == 'ubuntu-latest' && matrix.arch == 'x86_64' && 'linux-x86_64' || matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64' && 'linux-arm64' || matrix.os == 'macos-latest' && 'macos-arm64' || 'windows-x86_64' }}
          path: ./catsoup-${{ matrix.os == 'ubuntu-latest' && matrix.arch == 'x86_64' && 'linux-x86_64' || matrix.os == 'ubuntu-latest' && matrix.arch == 'arm64' && 'linux-arm64' || matrix.os == 'macos-latest' && 'macos-arm64' || 'windows-x86_64.exe' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Set up GitHub CLI
        uses: actions/setup-go@v5
        with:
          go-version: "^1.18"

      - name: Get Workflow Run URL
        id: get_run_url
        run: echo "RUN_URL=${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}" >> $GITHUB_ENV

      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} \
            --repo "${{ github.repository }}" \
            --title "Release ${{ github.ref_name }}" \
            --notes "Workflow logs: ${{ env.RUN_URL }}" \
            --generate-notes
          gh release upload ${{ github.ref_name }} ./artifacts/catsoup-linux-x86_64/catsoup-linux-x86_64
          gh release upload ${{ github.ref_name }} ./artifacts/catsoup-linux-arm64/catsoup-linux-arm64
          gh release upload ${{ github.ref_name }} ./artifacts/catsoup-macos-arm64/catsoup-macos-arm64
          gh release upload ${{ github.ref_name }} ./artifacts/catsoup-windows-x86_64/catsoup-windows-x86_64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
