name: Build/Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt-get update && sudo apt-get install -y build-essential

      - name: Set up build environment (Windows)
        if: matrix.os == 'windows-latest'
        run: choco install make

      - name: Set up build environment (macOS)
        if: matrix.os == 'macos-latest'
        run: brew install make

      - name: Build project
        run: make

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: catsoup-binary-${{ matrix.os }}
          path: ./catsoup

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: catsoup-binary-ubuntu-latest
          path: ./catsoup-ubuntu
        # ...repeat for windows-latest and macos-latest...

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release v${{ github.run_number }}
          draft: false
          prerelease: false

      - name: Upload binaries to release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./catsoup-ubuntu
          asset_name: catsoup-ubuntu
          asset_content_type: application/octet-stream
        # ...repeat for windows and macOS binaries...
