name: Build/Release

on:
  pull_request:
    branches:
      - main
  push:
    tags:
      - "v*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64
          - os: ubuntu-latest
            arch: arm64
          - os: macos-latest
            arch: arm64
          - os: windows-latest
            arch: x86_64
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up build environment
        run: |
          if [ "${{ matrix.os }}" == "ubuntu-latest" ]; then
            sudo apt-get update && sudo apt-get install -y build-essential
          elif [ "${{ matrix.os }}" == "macos-latest" ]; then
            brew install make
          elif [ "${{ matrix.os }}" == "windows-latest" ]; then
            choco install make
          fi

      - name: Build project
        run: make TARGET_ARCH=${{ matrix.arch }}

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os == 'ubuntu-latest' && 'catsoup-linux-' || matrix.os == 'macos-latest' && 'catsoup-macos-' || 'catsoup-windows-' }}${{ matrix.arch }}
          path: ./catsoup-${{ matrix.os == 'ubuntu-latest' && 'linux-' || matrix.os == 'macos-latest' && 'macos-' || 'windows-' }}${{ matrix.arch }}${{ matrix.os == 'windows-latest' && '.exe' || '' }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} --repo "${{ github.repository }}" --title "Release ${{ github.ref_name }}" --generate-notes
          gh release upload ${{ github.ref_name }} ./artifacts/catsoup-linux-arm64 ./artifacts/catsoup-linux-x86_64
          gh release upload ${{ github.ref_name }} ./artifacts/catsoup-macos-arm64
          gh release upload ${{ github.ref_name }} ./artifacts/catsoup-windows-x86_64.exe
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
